[package]
name = "selector4nix-system-test-nar-info-querying"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
selector4nix-system-test-common = { path = "../common" }
selector4nix-workspace-hack = { path = "../../crates/selector4nix-workspace-hack" }

anyhow = { workspace = true }
clap = { workspace = true }
fastrand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
which = { workspace = true }
