[package]
name = "selector4nix-web"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
selector4nix-core = { path = "../selector4nix-core" }
selector4nix-workspace-hack = { path = "../selector4nix-workspace-hack" }

anyhow = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
