[package]
name = "selector4nix-actor"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
selector4nix-workspace-hack = { path = "../selector4nix-workspace-hack" }

dashmap = { workspace = true }
futures = { workspace = true }
moka = { workspace = true }
tokio = { workspace = true }
