[package]
name = "selector4nix"
description = "Nix substituter proxy with parallel cache queries and latency-aware selection"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
selector4nix-actor = { path = "../selector4nix-actor" }
selector4nix-core = { path = "../selector4nix-core" }
selector4nix-db = { path = "../selector4nix-db" }
selector4nix-streaming = { path = "../selector4nix-streaming" }
selector4nix-web = { path = "../selector4nix-web" }
selector4nix-workspace-hack = { version = "0.0.0", path = "../selector4nix-workspace-hack" }

anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
redb = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-oslog = { workspace = true }
tracing-subscriber = { workspace = true }
