name: Upload Cache

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: aarch64-darwin
            runner: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: selector4nix
          extraPullNames: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build selector4nix
        run: |
          nix build ".#packages.${{ matrix.system }}.selector4nix" -L --no-link --print-out-paths
